//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SkillsManagementPlan.DB.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class Activity
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Activity()
        {
            this.ParticipantTypes = new HashSet<ParticipantType>();
        }
    
        public int ID { get; set; }
        public string Name { get; set; }
        public string Description { get; set; }
        public System.DateTime DateTimeStart { get; set; }
        public System.DateTime DateTimeEnd { get; set; }
        public int LocationID { get; set; }
        public int ResultTypeID { get; set; }
        public int ResponsibleID { get; set; }
        public int PlanID { get; set; }
        public int ActivityTypeID { get; set; }
    
        public virtual ActivityType ActivityType { get; set; }
        public virtual Location Location { get; set; }
        public virtual ParticipantType ParticipantType { get; set; }
        public virtual Plan Plan { get; set; }
        public virtual ResultType ResultType { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ParticipantType> ParticipantTypes { get; set; }
    }
}
