//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SkillsManagementPlan.DB.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class Timezone
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Timezone()
        {
            this.Plans = new HashSet<Plan>();
        }
    
        public int ID { get; set; }
        public int Identify { get; set; }
        public string Abbreviation { get; set; }
        public long StartOfCounting { get; set; }
        public long GreenwichOffset { get; set; }
        public bool SummerTime { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Plan> Plans { get; set; }
    }
}
