//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SkillsManagementPlan.DB.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class Zone
    {
        public int ID { get; set; }
        public string CountryCode { get; set; }
        public string TimeZoneName { get; set; }
    
        public virtual Country Country { get; set; }
    }
}
